export const POST_COMMENT_VALUE_CHANGE = 'POST_COMMENT_VALUE_CHANGE';
export const POST_COMMENT = 'POST_COMMENT';
export const LIKE_POST = 'LIKE_POST';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILUIRE = 'FETCH_POST_FAILUIRE';
